---
title: "SURV628 Group Assignment Code"
author: "Serena Lee"
date: "10/07/2025"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r, echo=FALSE} 
library(tidyverse)
library(haven)
library(srvyr)
```


```{r}
ess<- read_dta("ESS11.dta")

ess.interest <- ess|>
  select(cntry, region, domicil, atcherp, atchctr, vteurmmb, anweight)
```

variables: atcherp - attachment to Europe
           atchctr - attachment to Country
           

## Q1
Are European people more emotionally attached “Europe” or to their individual countries of residence?
```{r}
summary(ess.interest$atcherp, na.rm=T)
summary(ess.interest$atchctr, na.rm=T)
```
People are more emotionally attached to their country (median and mean are both higher).


## Q2
How does this vary across countries or regions?
```{r}

svyess <- ess|>
  as_survey_design(
    ids = psu,
    strata= stratum,
    weight= anweight,
    nest=T)|>
  select(cntry, atcherp, atchctr)|>
  mutate(difference = atchctr-atcherp)|>
  drop_na()

svyess.difference<- svyess|>
  group_by(cntry)|>
  summarize(mean=mean(difference))
  
ggplot(svyess.difference, aes(x=reorder(cntry, mean), y=mean))+
  geom_col()

```
